# Generated by Django 5.1.1 on 2024-09-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(max_length=500)),
                ('url', models.CharField(max_length=300)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='jornada/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='usuario/')),
            ],
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='jornada/')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioEsfera.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Conquista_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioEsfera.conquista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioEsfera.usuario')),
            ],
        ),
    ]
