# Generated by Django 5.1.1 on 2024-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
