# Generated by Django 5.1.1 on 2024-09-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0002_alter_conquista_descricao_alter_jogo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
