# Generated by Django 5.1.3 on 2024-11-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0004_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
