# Generated by Django 5.1.3 on 2024-11-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0005_remove_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
