# Generated by Django 5.1.3 on 2024-11-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0006_remove_usuario_imagem_remove_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_usuario',
        ),
    ]
