# Generated by Django 5.1.3 on 2024-11-21 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0007_remove_usuario_nome_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
