# Generated by Django 5.1.3 on 2024-11-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0008_conquista_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conquista',
            name='usuario',
        ),
    ]
