# Generated by Django 5.1.3 on 2024-11-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0013_alter_usuario_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem_avatar',
            name='usuario_imagem',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
