# Generated by Django 5.1.3 on 2024-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0014_imagem_avatar_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao_conquista',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
