# Generated by Django 5.1.3 on 2024-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioEsfera', '0016_alter_usuario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='images/cebolo_perfil.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='descricao_conquista',
            field=models.CharField(blank=True, default='Aperte em uma conquista que você ganhou e vejá o que acontece ;)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='Coloque_o_seu_email@email.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=18, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, default='Outros', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulo_conquista',
            field=models.CharField(blank=True, default='Novato', max_length=150, null=True),
        ),
    ]
